### ISSUE TITLE
npm support

### ISSUE THREAD

**Issue by itsmepetrov** [boazsender/backbone.routefilter#30]
Can you host it on npm for browserify support?

**Comment by anextro** [comment]
Is there browserify support for this?
I've tried to shim it but it still does not resolve

**Comment by stevewillard** [comment]
+1 please add to NPM

**Comment by anextro** [comment]
I ended up just using it successfully by using the alias option in browserify. This allows me to do require('routefilter'); and it resolves fine.

**Comment by stevewillard** [comment]
Was able to get this to work in Webpack using the alias feature, too, but I would prefer to just rely on NPM instead of Bower.

**Comment by Sinewyk** [comment]
nothing stops you from putting in npm
`"backbone.routefilter": "boazsender/backbone.routefilter#7769da5b3edb34d23926aaecdac5478489de4e18",
`
